### ISSUE TITLE
Not working with Symfony 3

### ISSUE THREAD

**Issue by qweluke** [vmeretail/multi-tenancy-bundle#41]
Symfony 3.2 throws this error:

> FatalThrowableError in EntityRepository.php line 64:
> Type error: Argument 2 passed to Doctrine\ORM\EntityRepository::__construct() must be an instance of Doctrine\ORM\Mapping\ClassMetadata, none given, called in /home/luke/wwwdata/nauka/bitbucket/workskedge/var/cache/dev/appDevDebugProjectContainer.php on line 4404

**Comment by stevergill** [comment]
Hi @qweluke unfortunately we're not maintaining this, because we've moved to Laravel now.

I'm not sure, but maybe some of the forks have continued support?

**Comment by qweluke** [comment]
@stevergill thanks for an answer.
I think that it would be nice if you add that information to the docs.
Regards

**Comment by stevergill** [comment]
@qweluke you're right, good point. We'll get that done.

**Comment by stevergill** [comment]
@pmartelletti whats the latest Symfony version we support here?

**Comment by pmartelletti** [comment]
@qweluke we only support until symfony 2. However, I think you can use this fork, that supports Symfony 3:

https://github.com/develth/multi-tenancy-bundle
